[env]
LIBTORCH = { value = ".venv/lib/python3.10/site-packages/torch", relative = true }

[build]
rustflags = [
  "-C",
  "link-arg=-Wl,--disable-new-dtags",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/torch/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/torch/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/onnxruntime/capi",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/onnxruntime/capi",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/nvidia/cublas/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/nvidia/cublas/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/nvidia/cuda_nvrtc/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/nvidia/cuda_nvrtc/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/nvidia/curand/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/nvidia/curand/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/nvidia/cufft/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/nvidia/cufft/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../.venv/lib/python3.10/site-packages/nvidia/cudnn/lib",
  "-C",
  "link-arg=-Wl,-rpath,$ORIGIN/../../../.venv/lib/python3.10/site-packages/nvidia/cudnn/lib",
]
